//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYQERP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSet
    {
        //public int Id { get; set; }
        public string Contacts { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string CompanyAddress { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string AddUserName { get; set; }
    }
}
