//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYQERP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliverySet()
        {
            this.DeliveryDetailSet = new HashSet<DeliveryDetailSet>();
        }
    
        //public int Id { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string Customer { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string TotalAmountUp { get; set; }
        public string Sender { get; set; }
        public string Manager { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string ModifyUserName { get; set; }
        public string SerialNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetailSet> DeliveryDetailSet { get; set; }
    }
}
