//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYQERP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementSet()
        {
            this.BomDetailSet = new HashSet<BomDetailSet>();
            this.PartDetailSet = new HashSet<PartDetailSet>();
            this.ProductDetailSet = new HashSet<ProductDetailSet>();
            this.StockInSet = new HashSet<StockInSet>();
            this.StockSet = new HashSet<StockSet>();
            this.StockOutSet = new HashSet<StockOutSet>();
            this.PickSet = new HashSet<PickSet>();
        }
    
        //public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string AddUserName { get; set; }
        public string ModifyUserName { get; set; }
        public int ShelfId { get; set; }
        public string UnitTypeCode { get; set; }
        public double WarningQuantity { get; set; }
        public string Remark { get; set; }
        public double PickQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BomDetailSet> BomDetailSet { get; set; }
        public virtual ShelfSet ShelfSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartDetailSet> PartDetailSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetailSet> ProductDetailSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInSet> StockInSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockSet> StockSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutSet> StockOutSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickSet> PickSet { get; set; }
    }
}
