//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYQERP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuSet()
        {
            this.RoleMenuSet = new HashSet<RoleMenuSet>();
            this.MenuOperSet = new HashSet<MenuOperSet>();
        }
    
        //public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string ParentCode { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public int MenuLevel { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string IconClass { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string ModifyUserName { get; set; }
        public bool ShowInMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMenuSet> RoleMenuSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuOperSet> MenuOperSet { get; set; }
    }
}
