//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYQERP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickSet()
        {
            this.StockOutSet = new HashSet<StockOutSet>();
        }
    
        //public int Id { get; set; }
        public int ElementId { get; set; }
        public Nullable<int> BomId { get; set; }
        public string PartCode { get; set; }
        public double Quantity { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string AddUserName { get; set; }
        public bool IsFeedback { get; set; }
        public double StockOutQuantity { get; set; }
        public Nullable<System.DateTime> StockOutTime { get; set; }
        public string StockOutUserName { get; set; }
        public int ParentId { get; set; }
    
        public virtual BomSet BomSet { get; set; }
        public virtual ElementSet ElementSet { get; set; }
        public virtual PickMainSet PickMainSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutSet> StockOutSet { get; set; }
    }
}
