//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYQERP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReportSet
    {
        //public int Id { get; set; }
        public string AfterSales { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string CustomerLevel { get; set; }
        public string Company { get; set; }
        public string SaleLeader { get; set; }
        public string PayDate { get; set; }
        public string PayWay { get; set; }
        public string CustomerType { get; set; }
        public string MachineType { get; set; }
        public string Model { get; set; }
        public string GoodsSpec { get; set; }
        public Nullable<int> GoodsNum { get; set; }
        public Nullable<decimal> TaxPrice { get; set; }
        public Nullable<decimal> AllTaxPrice { get; set; }
        public Nullable<decimal> LogisticsCost { get; set; }
        public Nullable<decimal> NoTaxPrice { get; set; }
        public string Invoice { get; set; }
        public string DeliveryNote { get; set; }
        public string Billing { get; set; }
        public string MachineNo { get; set; }
        public string OrderNo { get; set; }
        public string Remark { get; set; }
        public string Contacts { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string CompanyAddress { get; set; }
        public string Fax { get; set; }
        public string Bonus { get; set; }
        public string LogisticsCompany { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string AddUserName { get; set; }
        public System.Guid GroupGuid { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string ModifyUserName { get; set; }
    }
}
